@startuml

actor Shopper
participant Frontend
participant Klarna
participant Centra



|||
group Payment
Shopper -> Frontend: proceed to payment
activate Frontend

|||
Frontend -> Klarna: SDK.authorize(authorizePayload)
activate Klarna
Klarna -> Frontend: success callback(authorization_token)
deactivate Klarna
|||
Frontend -> Centra: POST /payment-result
deactivate Frontend
activate Centra
Centra -> Klarna: createOrder(authorization_token)
activate Klarna
Klarna --> Centra: success
deactivate Klarna
Centra -> Klarna: getSession()
activate Klarna
Klarna -> Centra: sessionResponse()
deactivate Klarna
Centra -> Centra: finalizeOrder(addressFromKlarnaSession)

Centra -> Frontend: POST /payment-result response - order placed
deactivate Centra
Frontend -> Shopper: Redirect to paymentSuccessPage

|||
end

@enduml
