@startuml

participant Frontend
participant Klarna
participant Centra
Frontend <-> Klarna: Klarna Payments SDK
Frontend <-> Centra: D2C APIs (Shop API/Checkout API)
Centra <-> Klarna: Klarna Payments API

@enduml
